import {
    Atom,
    BarChart3,
    BookOpen,
    Bot,
    Box,
    Boxes,
    Brain,
    Calculator,
    Calendar,
    Camera,
    Clapperboard,
    Cloud,
    Code,
    Compass,
    CreditCard,
    Database,
    Download,
    FilePen,
    FileSpreadsheet,
    FileText,
    FileType,
    Film,
    FolderKanban,
    GitBranch,
    Globe,
    GraduationCap,
    Headset,
    HeartPulse,
    Image as ImageIcon,
    KeyRound,
    Languages,
    Layers,
    Lightbulb,
    LineChart,
    Mail,
    Map,
    Megaphone,
    MessageSquare,
    Music,
    Palette,
    PenTool,
    Plug,
    Presentation,
    Puzzle,
    Rocket,
    Scale,
    Search,
    Send,
    Server,
    Share2,
    Sheet,
    Smartphone,
    Sparkles,
    Swords,
    Target,
    UserPlus,
    UserSearch,
    Users,
    Video,
    Wand,
    Webhook,
    Wrench,
    Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * 图标注册表：数据文件只保存字符串名，组件在此统一解析为 lucide 组件，
 * 保证数据层与 UI 层解耦，也避免在每个数据文件里重复 import 大量图标。
 */
export const iconMap: Record<string, LucideIcon> = {
    atom: Atom,
    barChart3: BarChart3,
    bookOpen: BookOpen,
    bot: Bot,
    box: Box,
    boxes: Boxes,
    calculator: Calculator,
    brain: Brain,
    calendar: Calendar,
    camera: Camera,
    clapperboard: Clapperboard,
    cloud: Cloud,
    code: Code,
    compass: Compass,
    creditCard: CreditCard,
    database: Database,
    download: Download,
    filePen: FilePen,
    fileSpreadsheet: FileSpreadsheet,
    fileText: FileText,
    fileType: FileType,
    film: Film,
    folderKanban: FolderKanban,
    gitBranch: GitBranch,
    globe: Globe,
    graduationCap: GraduationCap,
    headset: Headset,
    heartPulse: HeartPulse,
    image: ImageIcon,
    keyRound: KeyRound,
    languages: Languages,
    layers: Layers,
    lightbulb: Lightbulb,
    lineChart: LineChart,
    mail: Mail,
    map: Map,
    megaphone: Megaphone,
    messageSquare: MessageSquare,
    music: Music,
    palette: Palette,
    penTool: PenTool,
    plug: Plug,
    presentation: Presentation,
    puzzle: Puzzle,
    rocket: Rocket,
    scale: Scale,
    search: Search,
    send: Send,
    server: Server,
    share2: Share2,
    sheet: Sheet,
    smartphone: Smartphone,
    sparkles: Sparkles,
    swords: Swords,
    target: Target,
    userPlus: UserPlus,
    userSearch: UserSearch,
    users: Users,
    video: Video,
    wand: Wand,
    webhook: Webhook,
    wrench: Wrench,
    zap: Zap,
};

export function resolveIcon(name: string): LucideIcon {
    return iconMap[name] ?? Sparkles;
}
